/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package estoquem;


import java.util.ArrayList;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class AppTest {
    Estoque est = new Estoque();
    
     @BeforeEach
     
     public void criar(){
        est = new Estoque();
    }
     
    @Test
    public void adicionarProdutoTest(){
        est.adicionarProduto("Pao", 2);
        //String nome = est.produtoMaisEstocado();
        assertEquals(2, est.Consultar("Pao"));
    }
    
    @Test
    public void testConsultar(){
        est.adicionarProduto("Pao", 2);
        assertEquals(2, est.Consultar("Pao"),"Erro");
    }
    
    @Test
    public void removerProdutoTest(){
        est.adicionarProduto("Pao", 2);
        est.removerProduto("Pao", 1);
        assertEquals(1, est.Consultar("Pao"),"Erro");
    }
    
    
    
    @Test
    public void limparTest(){
       
        est.limparEstoque();
    }

       }
