/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cadastro;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;

class AppTest {
    
    
   
    @Test
    public void testValidarNome() {
        Cadastro cadastro = new Cadastro("Joao", "senha123", "joao@email.com");
        assertTrue(cadastro.validarNome("Maria"));
        assertFalse(cadastro.validarNome(null));
    }

    @Test
    public  void testValidarEmail() {
        Cadastro cadastro = new Cadastro("Joao", "senha123", "joao@email.com");
        assertTrue(cadastro.validarEmail("Joao@email.com"));
        
    }

    @Test
    public  void testValidarSenha() {
        Cadastro cadastro = new Cadastro("Joao", "senha123", "joao@email.com");
        assertTrue(cadastro.validarSenha("senha123"));
        assertFalse(cadastro.validarSenha("12345"));
    }
}
  
    
    
